import type { Config } from 'tailwindcss'

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#5E35B1',
        secondary: '#00897B',
        surface: '#FFFFFF',
        'surface-dim': '#E0E0E0',
        'surface-bright': '#F5F5F5',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F5F5F5',
        'surface-container': '#EEEEEE',
        'surface-container-high': '#E0E0E0',
        'surface-container-highest': '#BDBDBD',
        'on-surface': '#212121',
        'on-surface-variant': '#424242',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#F5F5F5',
        outline: '#757575',
        'outline-variant': '#E0E0E0',
        'surface-tint': '#5E35B1',
        'on-primary': '#FFFFFF',
        'primary-container': '#EDE7F6',
        'on-primary-container': '#311B92',
        'inverse-primary': '#B39DDB',
        'on-secondary': '#FFFFFF',
        'secondary-container': '#E0F2F1',
        'on-secondary-container': '#004D40',
        tertiary: '#616161',
        'on-tertiary': '#FFFFFF',
        'tertiary-container': '#EEEEEE',
        'on-tertiary-container': '#212121',
        error: '#D32F2F',
        'on-error': '#FFFFFF',
        'error-container': '#FFEBEE',
        'on-error-container': '#B71C1C',
        'primary-fixed': '#EDE7F6',
        'primary-fixed-dim': '#D1C4E9',
        'on-primary-fixed': '#311B92',
        'on-primary-fixed-variant': '#4527A0',
        'secondary-fixed': '#E0F2F1',
        'secondary-fixed-dim': '#B2DFDB',
        'on-secondary-fixed': '#004D40',
        'on-secondary-fixed-variant': '#00695C',
        'tertiary-fixed': '#EEEEEE',
        'tertiary-fixed-dim': '#E0E0E0',
        'on-tertiary-fixed': '#212121',
        'on-tertiary-fixed-variant': '#424242',
        background: '#FAFAFA',
        'on-background': '#212121',
        'surface-variant': '#EEEEEE',
        'border-divider': '#E0E0E0',
        'text-secondary': '#616161',
        'text-muted': '#9E9E9E',
      },
      fontFamily: {
        newsreader: ['Newsreader', 'serif'],
        inter: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        card: '16px',
        input: '12px',
        sheet: '24px',
      },
      spacing: {
        'edge': '24px',
        'block-gap': '24px',
        'nav-height': '72px',
        'header-height': '56px',
      },
      boxShadow: {
        'crisis': '0 4px 12px 0 rgba(0, 0, 0, 0.08)',
      }
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
} satisfies Config
